name: sentiment_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - scikit-learn==1.7.0
      - optuna
      - prefect
      - pandas
      - nltk
      - flask
      - joblib